version: '3'
services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - .:/var/www
    depends_on:
      - db
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.conf:/ect/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  # ------------------------
  # phpmyadminを動かすコンテナ
  # ------------------------
  phpmyadmin:
    #DockerHubからimageをダウンロード
    image: phpmyadmin/phpmyadmin:5
    #コンテナの名前
    container_name: phpmyadmin
    #コンテナと他のサービスを繋げる
    links:
      - db
    #localhost:8080でphpmyadminの管理画面に接続
    ports:
      - 8080:80
    #セッション情報をボリュームに設定して永続化
    volumes:
      - .docker/phpmyadmin/sessions:/sessions
